export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";
export const GET_PHOTOS_FAILED = "GET_PHOTOS_FAILED";
export const UPLOAD_PHOTOS_INPROGRESS = "UPLOAD_PHOTOS_INPROGRESS";
export const UPLOAD_PHOTOS_SUCCESS = "UPLOAD_PHOTOS_SUCCESS";
export const UPLOAD_PHOTOS_FAILED = "UPLOAD_PHOTOS_FAILED";
